[profile.default]
src = 'contracts/src'
test = 'contracts/test'
out = 'contracts/out'
libs = ['contracts/lib']
solc = '0.8.19'
remappings = [
  'ds-test/=lib/forge-std/lib/ds-test/src/',
  'solady/=lib/solady/',
  'seaport-core/=lib/seaport-core/',
  'seaport-sol/=lib/seaport-sol/',
  'seaport-types/=lib/seaport-types/'
]


# See more config options https://github.com/foundry-rs/foundry/tree/master/config